# Generated by Django 5.2.17 on 2026-08-28 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_geofence_radius", models.IntegerField(default=75)),
                ("max_allowed_gps_accuracy", models.IntegerField(default=40)),
                ("strict_geofence_camera_lock", models.BooleanField(default=True)),
                ("working_hours_start", models.TimeField(default="08:00")),
                ("working_hours_end", models.TimeField(default="18:00")),
                ("late_tolerance_minutes", models.IntegerField(default=15)),
                (
                    "company_name",
                    models.CharField(default="Staff Tracker", max_length=200),
                ),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="company/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "instructions_json",
                    models.TextField(
                        default="[]", help_text="JSON list of instructions"
                    ),
                ),
                ("site_name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("geofence_radius", models.IntegerField(default=75)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("date", models.DateField()),
                ("require_selfie", models.BooleanField(default=True)),
                ("require_checkout", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("CHECKED_IN", "Checked In"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="UPCOMING",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_staff",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckInRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("check_in_lat", models.FloatField()),
                ("check_in_lng", models.FloatField()),
                ("accuracy", models.FloatField()),
                ("distance_from_center", models.FloatField()),
                ("is_inside_geofence", models.BooleanField(default=True)),
                (
                    "selfie",
                    models.ImageField(
                        blank=True, null=True, upload_to="selfies/checkin/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("AWAITING_SELFIE", "Awaiting Selfie"),
                            ("COMPLETED", "Completed"),
                            ("REUPLOAD_REQUESTED", "Re-upload Requested"),
                        ],
                        default="PENDING_APPROVAL",
                        max_length=30,
                    ),
                ),
                ("status_notes", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("check_out_timestamp", models.DateTimeField(blank=True, null=True)),
                ("check_out_lat", models.FloatField(blank=True, null=True)),
                ("check_out_lng", models.FloatField(blank=True, null=True)),
                ("check_out_accuracy", models.FloatField(blank=True, null=True)),
                ("check_out_notes", models.TextField(blank=True, null=True)),
                (
                    "check_out_selfie",
                    models.ImageField(
                        blank=True, null=True, upload_to="selfies/checkout/"
                    ),
                ),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="staff_app.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STAFF", "Staff"),
                            ("ADMIN", "Admin"),
                            ("SUPER_ADMIN", "Super Admin"),
                        ],
                        default="STAFF",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("joined_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
