# Generated by Django 5.2.15 on 2026-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShareInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock",
                    models.CharField(
                        help_text="Stock symbol", max_length=20, unique=True
                    ),
                ),
                ("no_of_kitta", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["stock"],
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Transaction date (can be Nepali calendar string)"
                    ),
                ),
                (
                    "symbol",
                    models.CharField(help_text="Stock symbol e.g. PRVU", max_length=20),
                ),
                ("shares", models.PositiveIntegerField()),
                (
                    "buying_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "buy_amount_with_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sell_amount_after_tax",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Holding", "Holding"),
                            ("Sold", "Sold"),
                            ("Loss", "Loss"),
                        ],
                        default="Holding",
                        max_length=20,
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Pradeep / Pawan",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "symbol"],
            },
        ),
    ]
