# Generated by Django 5.2.15 on 2026-07-19 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('deposits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='deposit_month',
        ),
        migrations.AddField(
            model_name='deposit',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank', 'Bank Transfer')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='deposit',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='saving_month',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='deposit',
            name='saving_year',
            field=models.PositiveIntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='deposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='deposits/'),
        ),
        migrations.AddConstraint(
            model_name='deposit',
            constraint=models.UniqueConstraint(fields=('member', 'saving_year', 'saving_month'), name='unique_member_month_deposit'),
        ),
    ]
