# Generated by Django 5.2.15 on 2026-08-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "deposits",
            "0002_alter_deposit_options_remove_deposit_deposit_month_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="saving_month",
            field=models.PositiveSmallIntegerField(default=8),
        ),
    ]
