# Generated by Django 5.2.15 on 2026-08-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="remaining_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="member",
            name="remaining_days_updated_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
