# Generated by Django 5.2.15 on 2026-08-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_member_remaining_days_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remaining_days", models.IntegerField(default=0)),
                ("remaining_days_updated_at", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
