# Generated by Django 5.2.15 on 2026-08-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_globalsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsetting",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qr/"),
        ),
    ]
