# Generated by Django 5.2.15 on 2026-08-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_relateddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="gov_id_back",
            field=models.ImageField(blank=True, null=True, upload_to="gov_ids/"),
        ),
        migrations.AddField(
            model_name="member",
            name="gov_id_front",
            field=models.ImageField(blank=True, null=True, upload_to="gov_ids/"),
        ),
    ]
