# Generated by Django 5.2.15 on 2026-08-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Borrower's full name", max_length=150),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("disbursement_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Closed", "Closed")],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "interest_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "annual_interest_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.12,
                        help_text="e.g. 0.12 for 12%",
                        max_digits=5,
                    ),
                ),
                (
                    "tenure_years",
                    models.DecimalField(decimal_places=2, default=0.5, max_digits=4),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-disbursement_date"],
            },
        ),
    ]
