# Generated by Django 5.2.15 on 2026-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Closed", "Closed"),
                    ("Pending", "Pending"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
