# Generated by Django 5.2.15 on 2026-08-22 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications_app",
            "0002_meetingpoll_meetingpolloption_memberchatmessage_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingpoll",
            name="final_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="finalized_for_poll",
                to="notifications_app.meetingpolloption",
            ),
        ),
        migrations.AddField(
            model_name="meetingpolloption",
            name="suggested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggested_options",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
