# Generated by Django 5.2.15 on 2026-07-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True)),
                ('citizenship_no', models.CharField(blank=True, max_length=50)),
                ('joined_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('nominee_name', models.CharField(blank=True, max_length=150)),
                ('nominee_phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['member_id'],
            },
        ),
    ]
